{% set version = "1.2" %}

package:
  name: numpydoc
  version: {{ version }}

source:
  fn: numpydoc-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpydoc/numpydoc-{{ version }}.tar.gz
  sha256: 0cec233740c6b125913005d16e8a9996e060528afcb8b7cad3f2706629dfd6f7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - sphinx

test:
  imports:
    - numpydoc

about:
  home: https://github.com/numpy/numpydoc
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Numpy's Sphinx extensions

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
