{% set version = "1.3.1" %}

package:
  name: numpydoc
  version: {{ version }}

source:
  fn: numpydoc-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpydoc/numpydoc-{{ version }}.tar.gz
  sha256: 349ff29e00a5caf119141967e579f8f17b24d41c46740b13ea4e8dba9971b20f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools

  run:
    - python >=3.7
    - sphinx >=1.8
    - jinja2 >=2.10,<3.1

test:
  requires:
    - pip
  commands:
    - python -m pip check
  imports:
    - numpydoc

about:
  home: https://github.com/numpy/numpydoc
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Numpy's Sphinx extensions

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
